### ISSUE TITLE
Support new difficulty of V21

### ISSUE THREAD

**Issue by guilhermelawless** [guilhermelawless/nano-dpow#39]
https://docs.nano.org/integration-guides/work-generation/#difficulty-thresholds

Todo:
- [x] Notify services and known DPoW server replicas of plan
- [x] Update base difficulty, currently attached to https://github.com/Matoking/nanolib , potentially detach
- [x] Temporarily clamp max difficulty rather than returning an error (add a hint in response)
- [x] Lower the max multiplier to 1.0-2.0
- [x] Update only when epoch 2 starts

Won't be covered for now:
- Allow requesting receive difficulty

**Comment by adrianegraphene** [comment]
Thanks for the update. Temporarily clamping max difficulty is a good idea. 

We have min difficulty hardcoded in our requests and will update that as soon as you hit point 2, but others may not.

**Comment by guilhermelawless** [comment]
For anyone reading this, please note the repository is not yet updated with full support, though the running DPoW server is.
