### ISSUE TITLE
Add python3-hbmqtt as a dependency for Ubuntu

### ISSUE THREAD

**Issue by unyieldinggrace** [guilhermelawless/nano-dpow#43]
I tried running the client in Ubuntu, I found that I needed to install the python3-hbmqtt package before it would run. It would be a good idea to add this package as a dependency in the readme alongside ocl-icd-libopencl1.

**Comment by guilhermelawless** [comment]
Did you do this step?

`pip3 install --user -r requirements.txt` , in https://github.com/guilhermelawless/nano-dpow/tree/master/client#installation

**Comment by unyieldinggrace** [comment]
Whoops, must have skim-read over that part, my bad. I don't work much with python, not very familiar with pip! Sorry to disturb.

**Comment by guilhermelawless** [comment]
Not a problem, thanks for joining as a client!
